# **********************************************************************
#  Makefile for Relativitic MHD
# **********************************************************************

VPATH        +=   $(SRC)/RMHD/Radiation
INCLUDE_DIRS += -I$(SRC)/RMHD/Radiation
OBJ   +=  eddtensor.o flux_lim.o newtonsolve.o rad_errors.o \
          rad_hll.o rad_hllc.o rad_speed.o rad_tools.o rad_tvdlf.o \
          rad_flux.o rad_set_solver.o rad_sourcef.o rad_step.o
