# Add objects file for Power Law Cooling Source  
# Note: this module is handled differently from the 
# other cooling modules since integration is carried
# out analytically.

VPATH  += $(SRC)/Cooling/Power_Law
OBJ    += cooling.o  

