# Makefile for the CT module (MHD, RMHD, ResRMHD) Module 

VPATH += $(SRC)/MHD/CT
OBJ   += ct_field_average.o ct_emf.o ct_emf_average.o 
OBJ   += ct_flux.o ct_imex_update_ELR.o ct_maxwell_solver.o
OBJ   += emf_userdef.o ct_update.o ct_fill_mag_field.o 
HEADERS += ct.h
 

