# ----------------------------------------------------------------------
# Makeile for shearingbox module
# ----------------------------------------------------------------------

VPATH   += $(SRC)/MHD/ShearingBox
OBJ     += sb_flux.o sb_boundary.o sb_tools.o
HEADERS += shearingbox.h
 

