# ----------------------------------------------------------------------
# Included makefile for Particle module
# ----------------------------------------------------------------------

VPATH        += $(SRC)/Particles
INCLUDE_DIRS += -I$(SRC)/Particles

# -- General purpose source files --
OBJ += particles_boundary.o particles_deposit.o particles_init.o  \
       particles_load.o particles_mpi_datatype.o                  \
       particles_restart.o                  \
       particles_set.o particles_set_output.o                     \
       particles_tools.o plist_tools.o particles_weights.o        \
       particles_write_bin.o particles_write_data.o               \
       particles_write_trajectory.o particles_write_vtk.o              

HEADERS += particles.h






