# **********************************************************************
#  Makefile for Relativitic MHD
# **********************************************************************

VPATH        += $(SRC)/RMHD
INCLUDE_DIRS += -I$(SRC)/RMHD
OBJ   +=  eigenv.o fluxes.o four_vel.o  \
          hll_speed.o hll.o hllc.o hlld.o gforce.o  \
          mappers.o rhs.o rhs_source.o rmhd_energy_solve.o \
          rmhd_entropy_solve.o rmhd_pressure_fix.o \
          set_solver.o source.o tvdlf.o vel_limiter.o
 
