# **********************************************************************
# Makefile for Cooling module [driver]
# The specific module is specified in the user's makefile.
# **********************************************************************

VPATH   += $(SRC)/Cooling/
OBJ     += cooling_source.o cooling_ode_solver.o
HEADERS += cooling.h

 

